### ISSUE TITLE
gray screen after apple logo showed during install

### ISSUE THREAD

**Issue by yqtx528** [dongcodebmt/VX5-591G-OpenCore#10]
Hi, I used those files created a usb installer, but after apple logo showed, the screen turned gray and the mouse can move.
I have the same laptop with you, except that I don't repalce the wireless card yet, and only have 8GB memory, my bios firmware version is 1.0.6.
I don't know what happened, and the troubleshoot from opencore don't have the same case. I want to know if the wireless card must be replaced?

**Comment by dongcodebmt** [comment]
You don't need to replace the wireless card
Create your installer: https://dortania.github.io/OpenCore-Install-Guide/installer-guide/
Make sure you have a good USB and wait a moment. Maybe it's loading

**Comment by yqtx528** [comment]
> loading

Yes, I was used this link to create the installer. I tested with two USB, its the same. I waited for 15m then it seems fall into sleep mode.

**Comment by dongcodebmt** [comment]
I just checked it again. Looks like you did something wrong

- Download the latest version
`python macrecovery.py -b Mac-E43C1C25D4880AD6 -m 00000000000000000 download`
- Format USB to FAT32
- Create `com.apple.recovery.boot` folder in USB
- Copy `BaseSystem .chunklist` and `BaseSystem .dmg` into `com.apple.recovery.boot`
- Copy EFI in X86 to USB
- Delete everything in EFI / OC then copy files in my repo

**Comment by yqtx528** [comment]
> * Copy EFI in X86 to USB

why X86? I copied those from X64.

**Comment by dongcodebmt** [comment]
> why X86? I copied those from X64.

I'm sorry. X64 to be exact

**Comment by yqtx528** [comment]
Hi, I tried again exactly what U post, but still the same. 
I wonder what kind of mouse do U use, 'cause if I don't plugin a mouse, there will be a picture prompt to plugin a mouse, but once I plug my wireless mouse, the screen turn gray.

**Comment by dongcodebmt** [comment]
I am using an ASUS GT200 mouse. But I can use the touchpad without a mouse
I think you should try upgrading BIOS
https://www.acer.com/ac/en/US/content/support-product/7094?b=1

If it still doesn't work. You should set up OpenCore yourself

**Comment by dongcodebmt** [comment]
Maybe my touchpad patch is not working on BIOS v1.06
You can also try with a wired mouse

**Comment by yqtx528** [comment]
I will try to update my bios to v1.08 today, but I need a windows OS first, currently I only installed a debian.
I don't have a wired mouse, need to buy one.

**Comment by yqtx528** [comment]
Well, I tried with a wired mouse and update bios to v1.0.8, still the same result.
Dose it related to  hdd? I replaced the  origin one with a smaller one.

**Comment by yqtx528** [comment]
I just tried 10.15, it goes far than the 11, but grey screen at last then it showed a crash log:
[Uploading Installer Log 27-Nov-2020.txt…]()

**Comment by yqtx528** [comment]
well, I replaced the hdd back, still not work, Then I checked the hardware spec, my touchpad is different with yours. mine is SYNAUDB5.

**Comment by dongcodebmt** [comment]
Well, it's weird
I really don't know why. It worked great on my device without any problems
Touchpad will have different names depending on the BIOS settings and OS
Try with this config
https://www.dropbox.com/s/9jgtrwe7c7j665c/OC.zip?dl=0
I replaced the USB kext, removed touchpad patch. You will need mouse to install
Hope it works

**Comment by yqtx528** [comment]
Well, I tried, still not work. I checked my model no is N16C7. Maybe yours is different, since vx5-591g is a series.

**Comment by dongcodebmt** [comment]
Mine is also N16C7 - VX5-591G-58AX

**Comment by dongcodebmt** [comment]
I think it's the same. Some people use i7 processor. But it still works
Try vanilla: https://www.olarila.com/topic/6278-new-vanilla-olarila-images/

**Comment by yqtx528** [comment]
That's weird. I checked the touchpad in both windows and linux, its SYNA7DB5, but in windows it showes it's HID  compatible. Then I tried smbus and syna kext, but it all the same.

For 10.15, I created a debug version, It was crashed in user space macOS-Utilities, I can open disk utilities and see the disks.

I dont know what happened, I used to installed 10.12 with Clover back in 3 years ago, but I dont remember the recipies.

**Comment by yqtx528** [comment]
I set the touchpad mode to basic in bios and removed all the I2C kext and added the PS2 ones. Then the touchpad can work after the gray screen in 11 and the installer crash in 10.15. 
So I guess the problem not related to touchpad...

**Comment by dongcodebmt** [comment]
If you can boot to setup screen
Well, I don't think it's because of EFI
I think the problem is probably caused by your USB
It caused the installer to crash

Actually, I give up in this case
Try to install macOS then you can try my EFI

**Comment by yqtx528** [comment]
Well, I tried vanilla, It hungs very early, not reach the apple logo. I think I should give up now. Thanks for your patient.
