### ISSUE TITLE
No trackpad

### ISSUE THREAD

**Issue by Onlyfinn** [dongcodebmt/VX5-591G-OpenCore#11]
First, thank, i have exactly the same notebook, and im using your opencore folder, but i have not trackpad, i will really apreciate your help
[Send me MacBook-Pro-de-Samuel 2.zip](https://github.com/dongcodebmt/VX5-591G-OpenCore/files/5859466/Send.me.MacBook-Pro-de-Samuel.2.zip)

**Comment by dongcodebmt** [comment]
Maybe some models don't work with SSDT-TPAD.aml patch.
Remove it and replace it with XOSI patch

**Comment by Onlyfinn** [comment]
Will try

**Comment by Onlyfinn** [comment]
Didn't work, 0.6.5 / 0.6.6, i think its maybe a usb problem, cause when i put 2 devices on the usb 3.0, 1 stop work (At windows working perfectly) I dont understand nothing, its really sad

**Comment by dongcodebmt** [comment]
Let's try it: https://www.dropbox.com/s/2uqym363h6e6ohc/OC-VX15.zip?dl=0
I changed a few things. Hope it works

**Comment by Onlyfinn** [comment]
Solved!! Wow thank u, can u let your paypal? I wanna tip u for a coffee / beer, that really help me.
And the usb 3.0 issue its a little extrange, i cant connect Wifi Dongle and Pen Drive at usb 3.0 ports.
But i can connect Pendrive and iPhone, and at the usb 2.0 port the wifi.
Anyway thats perfect for me, really thanks. (Paypay address and close threat)

**Comment by dongcodebmt** [comment]
My paypal: https://www.paypal.me/dongdev
See USB ports patch guide: https://github.com/corpnewt/USBMap
Note that most wifi dongles require kext
