### ISSUE TITLE
Windows Boot Error

### ISSUE THREAD

**Issue by Onlyfinn** [dongcodebmt/VX5-591G-OpenCore#12]
Windows Boot with Acpi Patches
Here a good solution
(If (_OSI ("Darwin"))
https://www.dropbox.com/s/1jxr1qnekvwbgvz/SSDT-PNLF.aml?dl=0

DefinitionBlock ("", "SSDT", 2, "OCLT", "PNLF", 0x00000000)
{
    If (_OSI ("Darwin"))
    {
        Scope (_SB)
        {
            Device (PNLF)
            {
                Name (_ADR, Zero)  // _ADR: Address
                Name (_HID, EisaId ("APP0002"))  // _HID: Hardware ID
                Name (_CID, "backlight")  // _CID: Compatible ID
                Name (_UID, 0x10)  // _UID: Unique ID
                Method (_STA, 0, NotSerialized)  // _STA: Status
                {
                    Return (0x0B)
                }
            }
        }
    }
}

**Comment by Onlyfinn** [comment]
I posted before check, but still runing with patches

**Comment by dongcodebmt** [comment]
I don't understand why but all current patches work perfectly for me.
Can you tell me about model and BIOS version?

**Comment by dongcodebmt** [comment]
Looks like some of the other models of the VX15 are somewhat different. 
I have created a new branch. It will be compatible with more models.
Check this out: https://github.com/dongcodebmt/VX5-591G-OpenCore/tree/XOSI
Thank you

**Comment by Onlyfinn** [comment]
Checked and its perfect, mine is a vx 15 591g, now im trying to disable acpi inject when try to boot windows, u know how to do that?

**Comment by dongcodebmt** [comment]
Unfortunately there is no way.
OpenCore will inject everything.  However, it won't matter if you get it right
