### ISSUE TITLE
gray screen with mouse cursor on big sur recovery

### ISSUE THREAD

**Issue by bnsilvaa** [dongcodebmt/VX5-591G-OpenCore#14]
hey guys, in my case this [tip](https://www.reddit.com/r/hackintosh/comments/dcq0lv/macos_installer_and_post_installer_keeps_thinking/f2abv2r?utm_source=share&utm_medium=web2x&context=3) resolved the "gray screen with mouse" issue on big sur recovery, hope it helps someone else.

`NVRAM -> 7C436110-AB2A-4BBB-A880-FE41995C9F82 -> prev-lang:kbd -> 656e2d5553a3e`

![Captura de Tela 2021-02-18 às 13 49 11](https://user-images.githubusercontent.com/56141644/108391133-26160880-71f0-11eb-925a-241f067ab615.png)

**Comment by dorey973** [comment]
Hello,
Have you change something else from the file from github? what i've changed from the file : 
- I've generated Mac serial with MacBookPro14,3 (because on dortania MacBookPro14,3 is for Quad Core 45w | iGPU: HD 630 (my VX5-591G))
- change prev-lang:kbd -> 656e2d5553a3e
![Capture d’écran 2021-02-20 114307](https://user-images.githubusercontent.com/79217821/108594257-36a5ba80-7379-11eb-8943-1c8398a25465.png)
But still stuck "gray screen with mouse"

**Comment by dongcodebmt** [comment]
> hey guys, in my case this [tip](https://www.reddit.com/r/hackintosh/comments/dcq0lv/macos_installer_and_post_installer_keeps_thinking/f2abv2r?utm_source=share&utm_medium=web2x&context=3) resolved the "gray screen with mouse" issue on big sur recovery, hope it helps someone else.
> 
> `NVRAM -> 7C436110-AB2A-4BBB-A880-FE41995C9F82 -> prev-lang:kbd -> 656e2d5553a3e`
> 
> ![Captura de Tela 2021-02-18 às 13 49 11](https://user-images.githubusercontent.com/56141644/108391133-26160880-71f0-11eb-925a-241f067ab615.png)

Thanks you. I appreciate that


> Hello,
> Have you change something else from the file from github? what i've changed from the file :
> 
> * I've generated Mac serial with MacBookPro14,3 (because on dortania MacBookPro14,3 is for Quad Core 45w | iGPU: HD 630 (my VX5-591G))
> * change prev-lang:kbd -> 656e2d5553a3e
>   ![Capture d’écran 2021-02-20 114307](https://user-images.githubusercontent.com/79217821/108594257-36a5ba80-7379-11eb-8943-1c8398a25465.png)
>   But still stuck "gray screen with mouse"

- NVIDIA GTX 1050 on this laptop doesn't work with MacOS. So choose MacBookPro14,1 instead of MacBookPro14,3
[Choosing the right SMBIOS](https://dortania.github.io/OpenCore-Install-Guide/extras/smbios-support.html)
- Set String to Data. 656e2d5553a3e is Data not String

**Comment by dongcodebmt** [comment]
> hey guys, in my case this [tip](https://www.reddit.com/r/hackintosh/comments/dcq0lv/macos_installer_and_post_installer_keeps_thinking/f2abv2r?utm_source=share&utm_medium=web2x&context=3) resolved the "gray screen with mouse" issue on big sur recovery, hope it helps someone else.
> 
> `NVRAM -> 7C436110-AB2A-4BBB-A880-FE41995C9F82 -> prev-lang:kbd -> 656e2d5553a3e`
> 
> ![Captura de Tela 2021-02-18 às 13 49 11](https://user-images.githubusercontent.com/56141644/108391133-26160880-71f0-11eb-925a-241f067ab615.png)

Thank you. I appreciate that


> Hello,
> Have you change something else from the file from github? what i've changed from the file :
> 
> * I've generated Mac serial with MacBookPro14,3 (because on dortania MacBookPro14,3 is for Quad Core 45w | iGPU: HD 630 (my VX5-591G))
> * change prev-lang:kbd -> 656e2d5553a3e
>   ![Capture d’écran 2021-02-20 114307](https://user-images.githubusercontent.com/79217821/108594257-36a5ba80-7379-11eb-8943-1c8398a25465.png)
>   But still stuck "gray screen with mouse"

- NVIDIA GTX 1050 on this laptop doesn't work with MacOS. So choose MacBookPro14,1 instead of MacBookPro14,3
[Choosing the right SMBIOS](https://dortania.github.io/OpenCore-Install-Guide/extras/smbios-support.html)
- Set String to Data. 656e2d5553a3e is Data not String

**Comment by dorey973** [comment]
> > Hello,
> > Have you change something else from the file from github? what i've changed from the file :
> > 
> > * I've generated Mac serial with MacBookPro14,3 (because on dortania MacBookPro14,3 is for Quad Core 45w | iGPU: HD 630 (my VX5-591G))
> > * change prev-lang:kbd -> 656e2d5553a3e
> >   ![Capture d’écran 2021-02-20 114307](https://user-images.githubusercontent.com/79217821/108594257-36a5ba80-7379-11eb-8943-1c8398a25465.png)
> >   But still stuck "gray screen with mouse"
> 
>     * NVIDIA GTX 1050 on this laptop doesn't work with MacOS. So choose MacBookPro14,1 instead of MacBookPro14,3
>       [Choosing the right SMBIOS](https://dortania.github.io/OpenCore-Install-Guide/extras/smbios-support.html)
> 
>     * Set String to Data. 656e2d5553a3e is Data not String

Hi, thanks for the reply, 
- I've choose MacBookPro14,1
- 656e2d5553a3e with data : 
![Capture d’écran 2021-02-20 133719](https://user-images.githubusercontent.com/79217821/108597408-301f3f00-7389-11eb-9f43-25486d21b2b3.png)
So I've look for the dortania guide and I've tried : 
![image](https://user-images.githubusercontent.com/79217821/108597455-6bba0900-7389-11eb-865a-9560f45c249c.png)
Still stuck on the gray screen.

**Comment by dongcodebmt** [comment]
This problem only happens to some people and I don't know what the cause is.
Try this: https://github.com/dongcodebmt/VX5-591G-OpenCore/tree/XOSI

**Comment by bnsilvaa** [comment]
I only made the following changes (using OC Auxiliary Tools v0.6.7):

- Changed PlataformInfo serial, MBL, and UUID (MacBookPro14,1)
- Add itlwm_cc=[COUNTRY_CODE](http://xml.coverpages.org/country3166.html) to boot-args.
- Update [VoodooI2C 2.6.4](https://github.com/VoodooI2C/VoodooI2C/releases/tag/2.6.4) and [AirportItlwm v1.3.0-alpha](https://github.com/OpenIntelWireless/itlwm/releases/tag/v1.3.0-alpha) (working HT40 on 2.4Ghz wifi but still in alpha)
- Reset NVRAM and was able to load into recovery.

This is my [config.plist](https://github.com/dongcodebmt/VX5-591G-OpenCore/files/6015028/config.plist.zip), I only generated a new serial (MacBookPro14,1) before upload. You can try this one.

I did have the same issue on my first Big Sur USB, but then I was able to install it with a Mojave USB and update it to Big Sur.

**Comment by dorey973** [comment]
Okay, I think that I've solved the "grayscreen" problem by reseting NVRAM before run the stick.
But I've some graphic glitch : 
![C5BA061D-3766-4A48-A369-2F49CFC11951](https://user-images.githubusercontent.com/79217821/108599946-67dfb400-7394-11eb-9afe-aa9928731150.jpeg)
![8221EBD6-D022-4FE5-AB98-AE69FA330A10](https://user-images.githubusercontent.com/79217821/108599948-68784a80-7394-11eb-84a5-5a7a094a7452.jpeg)

**Comment by dorey973** [comment]
Okay, so I've managed to install MacOS on a drive, but when I reboot on Mac Installer, it is stuck on gray screen, guess that I'm cursed

**Comment by bnsilvaa** [comment]
> 
> * Set String to Data. 656e2d5553a3e is Data not String

thank you @dongcodebmt, I corrected my as well.

![Captura de Tela 2021-02-21 às 12 55 05](https://user-images.githubusercontent.com/56141644/108630555-168efd80-7444-11eb-875f-71640d2e5abe.png)

**Comment by dongcodebmt** [comment]
> Okay, so I've managed to install MacOS on a drive, but when I reboot on Mac Installer, it is stuck on gray screen, guess that I'm cursed

Try this config: [config.plist](https://drive.google.com/file/d/14YIdCEKnluuhY-JomkZf7Qgxe2TlFhqH/view?usp=sharing) (reset NVRAM before installing)

**Comment by marcoaleixo** [comment]
> > Okay, so I've managed to install MacOS on a drive, but when I reboot on Mac Installer, it is stuck on gray screen, guess that I'm cursed
> 
> Try this config: [config.plist](https://drive.google.com/file/d/14YIdCEKnluuhY-JomkZf7Qgxe2TlFhqH/view?usp=sharing) (reset NVRAM before installing)

this file was deleted :/

**Comment by dongcodebmt** [comment]
> > > Okay, so I've managed to install MacOS on a drive, but when I reboot on Mac Installer, it is stuck on gray screen, guess that I'm cursed
> > 
> > 
> > Try this config: [config.plist](https://drive.google.com/file/d/14YIdCEKnluuhY-JomkZf7Qgxe2TlFhqH/view?usp=sharing) (reset NVRAM before installing)
> 
> this file was deleted :/

I have found that some people have problems with the Big Sur installer that can be fixed by installing Mojave. They can then update to Big Sur.
Also try my installer. I have used it on my laptop without any problems.
[Use rufus to create your bootable USB](https://drive.google.com/file/d/1dladOA9X30nm0yqMbKSWH618MzuYA8sY/view?usp=sharing)

**Comment by marcoaleixo** [comment]
> > > > Okay, so I've managed to install MacOS on a drive, but when I reboot on Mac Installer, it is stuck on gray screen, guess that I'm cursed
> > > 
> > > 
> > > Try this config: [config.plist](https://drive.google.com/file/d/14YIdCEKnluuhY-JomkZf7Qgxe2TlFhqH/view?usp=sharing) (reset NVRAM before installing)
> > 
> > 
> > this file was deleted :/
> 
> I have found that some people have problems with the Big Sur installer that can be fixed by installing Mojave. They can then update to Big Sur.
> Also try my installer. I have used it on my laptop without any problems.
> [Use rufus to create your bootable USB](https://drive.google.com/file/d/1dladOA9X30nm0yqMbKSWH618MzuYA8sY/view?usp=sharing)

just to make sure. I need to format as MBR or GPT?
