### ISSUE TITLE
XOSI Update

### ISSUE THREAD

**Issue by Onlyfinn** [dongcodebmt/VX5-591G-OpenCore#15]
Hi! Can u update Xosi Branch? Thanks and sorry.

**Comment by dongcodebmt** [comment]
I've updated
https://github.com/dongcodebmt/VX5-591G-OpenCore/tree/XOSI

**Comment by Onlyfinn** [comment]
No trackpad with the new update

**Comment by Onlyfinn** [comment]
Acpi patch change _OSI to XOSI Find 5F4F5349 Replace 584F5349

**Comment by dongcodebmt** [comment]
Thanks. I fixed it
