### ISSUE TITLE
Xosi Branch

### ISSUE THREAD

**Issue by Onlyfinn** [dongcodebmt/VX5-591G-OpenCore#17]
I am very sorry to bother you again, I have downloaded master, and replaced Xosi folder, and that don't start at all. Vault error, is there a possibility to speak directly to you? With the 11.3 update I also had problems with the USB (Fixed) but I was looking forward to the update to 0.6.9 and it would be great to update. Thank you so much for your work.

**Comment by dongcodebmt** [comment]
Looks like you did something wrong.
Watch video to create your config: https://youtu.be/bIsj1rCC0vk
