### ISSUE TITLE
Macos Monterey Support

### ISSUE THREAD

**Issue by LFMAKER** [dongcodebmt/VX5-591G-OpenCore#18]
Hi, do you plan to add support for macos monterey?

**Comment by dongcodebmt** [comment]
I'm fixing a few issues.  
- MacOS Monterey restarts in about 3-5 minutes
- Intel wireless not working
- and some other problems

**Comment by dongcodebmt** [comment]
I updated latest kexts and edit config. Now it can work
- Intel 7265 not working. Only wifi can be used by HeliPort and itlwm. I haven't tried with another wireless card yet
- Slow startup. Takes about 2 minutes

**Comment by LFMAKER** [comment]
I'm having a slow start too. With my ssd nvme I'm taking approximately 1:30 minutes.

**Comment by dongcodebmt** [comment]
> I'm having a slow start too. With my ssd nvme I'm taking approximately 1:30 minutes.

Enabling automatic login will solve this problem
