### ISSUE TITLE
Cám ơn bạn về repo này 

### ISSUE THREAD

**Issue by vacnex** [dongcodebmt/VX5-591G-OpenCore#2]
Mình cũng dùng con acer vx5 cấu hình bạn, với EFI của bạn mình boot vô tư vào mac nhưng giờ mình đang làm lại cái usb boot catalina 10.15.6 mà chưa thành công bạn có thể chia sẽ EFI boot dùng opencore của bạn không ?
Cám ơn bạn!

**Comment by dongcodebmt** [comment]
> Mình cũng dùng con acer vx5 cấu hình bạn, với EFI của bạn mình boot vô tư vào mac nhưng giờ mình đang làm lại cái usb boot catalina 10.15.6 mà chưa thành công bạn có thể chia sẽ EFI boot dùng opencore của bạn không ?
> Cám ơn bạn!

Mình tạo bộ cài USB xong rồi boot bằng EFI trên ổ cứng luôn chứ mình không dùng EFI của USB nên không có đâu bạn.

**Comment by vacnex** [comment]
ồ đúng rồi, lúc mình dùng repo trước thì khi boot nó không hiện install macos mà sáng nay mình update từ bạn thì nó lại hiện từ usb của mình :v và mình cài đặt ok hết, cám ơn bạn nhé
Hình như usb 3.0 chưa patch được đúng không bạn ?
hình trên máy mình: https://imgur.com/a/TGi4NC3

**Comment by dongcodebmt** [comment]
> ồ đúng rồi, lúc mình dùng repo trước thì khi boot nó không hiện install macos mà sáng nay mình update từ bạn thì nó lại hiện từ usb của mình :v và mình cài đặt ok hết, cám ơn bạn nhé
> Hình như usb 3.0 chưa patch được đúng không bạn ?
> hình trên máy mình: https://imgur.com/a/TGi4NC3

Do mình không có thiết bị để thử nên đã tắt USB-C, các cổng USB còn lại thì mình đã patch ok hết: https://imgur.com/ZysoIgl

**Comment by vacnex** [comment]
Sao của mình 2 cái dưới cùng không hoạt động giống ảnh của bạn nhỉ ?
hình chụp hackintool máy mình https://imgur.com/a/AD0w5I6

**Comment by dongcodebmt** [comment]
> Sao của mình 2 cái dưới cùng không hoạt động giống ảnh của bạn nhỉ ?
> thiết bị pendrive là cái usb 3.0 mình cắm vào
> hình chụp hackintool máy mình https://imgur.com/a/AD0w5I6

Bạn thử USB khác xem. Nếu USB 2.0 thì nhận 2 cái đầu thôi. Vệ sinh chân cắm nữa có thể do chân cắm bụi bẩn.

**Comment by vacnex** [comment]
Các cổng SS01 SS02 không hiện khi mình thử usb khác đều là 3.0

**Comment by dongcodebmt** [comment]
> Các cổng SS01 SS02 không hiện khi mình thử usb khác đều là 3.0

Bạn xóa `USBMap.ext ` rồi thay bằng `USBInjectAll.kext` xem nó nhận đúng không nhé. Nhớ OC Snapshot

**Comment by vacnex** [comment]
Bác ơi hình như cái USB 3.0 của mình có vấn đề
https://imgur.com/a/JXT75JN
bên window cũng chỉ có tốc độ của 2.0 thậm chí chậm hơn ở tất cả các port ?

**Comment by dongcodebmt** [comment]
> Bác ơi hình như cái USB 3.0 của mình có vấn đề
> https://imgur.com/a/JXT75JN
> bên window cũng chỉ có tốc độ của 2.0 thậm chí chậm hơn ở tất cả các port ?

Bạn kiểm tra lại các chân usb vệ sinh lại cho sạch sẽ rồi thử lại nhé.

**Comment by vacnex** [comment]
Do con usb mình chưa định dạng lại nên cắm vào nó không nhận :v. Bạn có dùng facebook hay ở trong nhóm VNO-Hackintosh không? để tiện liên lạc.

**Comment by dongcodebmt** [comment]
> Do con usb mình chưa định dạng lại nên cắm vào nó không nhận :v. Bạn có dùng facebook hay ở trong nhóm VNO-Hackintosh không? để tiện liên lạc.

Mình có trong nhóm Hackintosh Vietnam thôi bạn. Có xin rồi nhưng mà họ không duyệt.
Facebook: https://fb.com/mr.dongbmt
