### ISSUE TITLE
Ethernet cable not work.

### ISSUE THREAD

**Issue by lehmartins17** [dongcodebmt/VX5-591G-OpenCore#3]
ethernet does not work. Is yours working? : '(
Hello again. Excellent job! You are very good.

**Comment by lehmartins17** [comment]
Bluetooth don't work too.

**Comment by dongcodebmt** [comment]
> ethernet does not work. Is yours working? : '(
> Hello again. Excellent job! You are very good.

It works for me. Try to download the latest kext and replace it.
https://imgur.com/quZlLEd

> Bluetooth don't work too.

Use kext IntelBluetoothFirmware if you have an Intel card. I replaced it with a real mac card. So this repo doesn't have any wifi or bluetooth kext

**Comment by lehmartins17** [comment]
I tried to use the IntelBluetooth project, but I was not successful! I don't know why it doesn't work, on the first startup it worked, right after it stopped! :(
But thanks for every contribution: D

> > ethernet does not work. Is yours working? : '(
> > Hello again. Excellent job! You are very good.
> 
> It works for me. Try to download the latest kext and replace it.
> https://imgur.com/quZlLEd
> 
> > Bluetooth don't work too.
> 
> Use kext IntelBluetoothFirmware if you have an Intel card. I replaced it with a real mac card. So this repo doesn't have any wifi or bluetooth kext

**Comment by dongcodebmt** [comment]
Check for USB patches. It could also be the cause. And check if the kext has been loaded

**Comment by lehmartins17** [comment]
Got it! It was USB mapping, thanks for the tip.
I hope the final version will come out soon, with a bug in the App Store don't download anything, say that the connection time has expired.

Thank you: D

> Check for USB patches. It could also be the cause. And check if the kext has been loaded
