### ISSUE TITLE
Screen blinks/flicker randomly

### ISSUE THREAD

**Issue by fbocolowski** [dongcodebmt/VX5-591G-OpenCore#4]
Hi there!

First of all I want to thank you for this repo sharing!!! It really encouraged me to try out OpenCore and I'm loving it!

I'm having an issue and hope you can help me or show me a path. Almost every 1~3 minutes with no reason, the screen goes quickly black and comes back, this only happens to the main laptop screen, not on HDMI. I own the VX15 i7 and I'm on 24GB RAM, all original parts except for SSD, SSD M2 and RAM. I still haven't installed it on the main drive, still booting from USB to get into MacOS.

Is there any tip or something I can try for solving this? I've seen a couple of videos talking about the 630 having some issues on Mac, but as you could do the full setup, I tought you could share something. :)

PS: This problem does not occur on Windows and Ubuntu.

**Comment by dongcodebmt** [comment]
It's weird because both the i5 and i7 are the HD630 with a device-id of 0x591B.
As far as I know it's a native device so there's no need to patch the framebuffer. Just adding Whatevergreen + Lilu kext is enough.
So the first thing I think you should try is patching the framebuffer.
Follow this guide to patch your framebuffer: [link](https://dortania.github.io/OpenCore-Install-Guide/config-laptop.plist/kaby-lake.html#deviceproperties)

PS: Do you use clover bootloader? Is it working properly?

**Comment by fbocolowski** [comment]
I'm using the latest OpenCore EFI combined with all of your repo files, nothing more. I was still booting from USB Bootloader, and just manually copied the USB EFI to the EFI partition from the macOS SSD.

I tried reading and watching some videos about the HD 630 and this framebuffer patches, but as I'm following your repo, I couldn't understand how to change the framebuffer data. Any tips on how to get further? I'm trying using OpenCore Configurator but no success.

I'm now using Clover, should I try it? Also, I'm using the latest Catalina 10.15.6 which I've downloaded using GibMacOS from a Windows machine. Should I try switching versions or even trying Big Sur?

**Comment by dongcodebmt** [comment]
Just follow Dortania guide
https://imgur.com/DxHbubT

Can try Big Sur if you want

**Comment by fbocolowski** [comment]
None of these worked. One thing I've noticed is that on one attempt of changing my SMBIOS to iMac 13, iMac 11 or MacBookPro 13 (another gen), the blink of the screen got wors, so I've had to revert back to yours plist.

This is a video showing what the blinking looks like: https://youtu.be/8RW2cK5r2Gg 
I have the original VX15 integrated screen 16' pol 60Hz 1080p.

**Comment by dongcodebmt** [comment]
Try this config: https://www.dropbox.com/s/3toqt5kpzqj1h95/config.plist?dl=0

**Comment by fbocolowski** [comment]
Didn't work. Also tried some combinations, such as this one: https://imgur.com/OmcjesD
Also tried combinations of "framebuffer-con1-enable", "framebuffer-con1-alldata" but no results.

**Comment by dongcodebmt** [comment]
"framebuffer-con1" for external monitors. So it won't work

Try copying to EFI then reboot and reset NVRAM.
If it still doesn't work, I don't know what to do either.

**Comment by fbocolowski** [comment]
Still no success. For now I'm using only my HDMI monitor ☹️
Another thing, how did you get Big Sur? Did you install it from separate USB/dmg or can I upgrade from Catalina to it?

**Comment by dongcodebmt** [comment]
You can upgrade in any way you can.
However, there may be some problems with the reboot process.
Just hold down the power button if it hangs for too long.

**Comment by fbocolowski** [comment]
Thanks for the help until now :)
I'm trying to reach more help.
Cloned your repo and opened an issue there with more info: https://github.com/fbocolowski/VX5-591G-OpenCore/issues/1
Also created a Reddit post asking for help: https://www.reddit.com/r/hackintosh/comments/j4854i/opencore_061_builtin_screen_blinks_on_acer_vx15/

I'm thinking of also opening requests to tonymacx86 Forum. Any other place you know I could reach?

**Comment by dongcodebmt** [comment]
Have you tried with SMBIOS MacBookPro14,3 yet? It has the same CPU as you
Try increasing VRAM to 2048MB
