### ISSUE TITLE
Future macOS upgrades and some questions

### ISSUE THREAD

**Issue by marcoaleixo** [dongcodebmt/VX5-591G-OpenCore#5]
Hi!
Thank you for this amazing repo.
I will try to install this hackintosh for the first time in my life, hehe.

My first question is: when Big Sur came out from beta, it will be possible to just upgrade or we need to make a fresh install?
My second question is: I don't have a Mac OS to build the Big Sur image, which version is compatible with this notebook besides Big Sur?
My third question: When I select "macOS Base Installer" the Apple logo appears and my notebook is rebooted. It's possible to turn on some verbose mode?

My notebook model VX5-591G too, and do you have a Discord or something like that?

Thank you.

**Comment by dongcodebmt** [comment]
> My first question is: when Big Sur came out from beta, it will be possible to just upgrade or we need to make a fresh install?

You don't need a fresh install. Just upgrade as usual

> My second question is: I don't have a Mac OS to build the Big Sur image, which version is compatible with this notebook besides Big Sur?

It has been tested with Catalina and Big Sur. You can get the installer using GibMacOS

> My third question: When I select "macOS Base Installer" the Apple logo appears and my notebook is rebooted. It's possible to turn on some verbose mode?

Add '-v' to config.plist>NVRAM>Add>7C436110-AB2A-4BBB-A880-FE41995C9F82>boot-args
See configuration details: https://dortania.github.io/OpenCore-Install-Guide/config-laptop.plist/kaby-lake.html#nvram

My discord: DongNoob#3763

**Comment by dongcodebmt** [comment]
Solved
