### ISSUE TITLE
Which wifi card should I get? BCM94360NG chip is turning on and off constantly.

### ISSUE THREAD

**Issue by alaturqua** [dongcodebmt/VX5-591G-OpenCore#6]
Hi I have the i7 version of this laptop. Which wifi card should I get to make it work with macos?

Thanks in advance!

**Comment by dongcodebmt** [comment]
I'm using BCM94360CS2 + Adapter. It works without kext
Wireless buyers guide: https://dortania.github.io/Wireless-Buyers-Guide/types-of-wireless-card/m2.html
If you want to use intel card. Refer to:
https://github.com/OpenIntelWireless/itlwm
https://github.com/OpenIntelWireless/HeliPort
https://github.com/OpenIntelWireless/IntelBluetoothFirmware

**Comment by alaturqua** [comment]
Would this fit into my Laptop BCM94360CS2 + Adapter?
It looks like a pci-e card. How did you fit it?

Do you have maybe pictures / any tutorial?

**Comment by dongcodebmt** [comment]
Your device and mine are the same. So it will fit
https://imgur.com/a/5MCl0Gg
It will be thicker. So remove the rubber piece from the lid

If you are worried, choose another m2 card as guide by dortania

**Comment by alaturqua** [comment]
Thank you very much for your help! You are the best.

**Comment by alaturqua** [comment]
@dongcodebmt 

I bought and installed the following wifi card.
https://www.amazon.de/gp/product/B083YXS7VF/ref=ppx_yo_dt_b_asin_image_o01_s00?ie=UTF8&psc=1

My issue is now. Wifi keeps disabling and enabling itself in a loop. 
I searched internet and reddit for a solution. But I couldn't find anything, which worked.

Do you know maybe what I can do to fix this?
Any Issues with kexts from this repo maybe? I am using them 1:1.

**Comment by dongcodebmt** [comment]
Do you have windows or linux to check?

**Comment by alaturqua** [comment]
I tested it on windows 10. It is working there. I had to install drivers from fenvi webpage. 

But wifi indicator on bottom right shows no signal even though I can clearly surf on web.

On macos it wifi is constantly restarting. After I installed usbinjectall.kext I was able to see Bluetooth as well and could connect to my airpods. But sound quality was bad.

**Comment by dongcodebmt** [comment]
You will need to contact the seller for assistance
Maybe the card is faulty. Need to exchange for another card

**Comment by alaturqua** [comment]
> You will need to contact the seller for assistance
> Maybe the card is faulty. Need to exchange for another card

Yes, I guess I have to send it back. It came from USA and I am in EU.

**Comment by dongcodebmt** [comment]
I bought it at an e-commerce site in vietnam
It is an old card but works fine with no problems

Note that you need to apply duct tape on the back of the adapter. Because it will contact the auxiliary board
The rubber piece on the lid needs to be removed to fit

**Comment by alaturqua** [comment]
I think I will order the same one again to see, if the other one was faulty. If it doesnt work again, I will send it back and use just a usb wifi dongle.

**Comment by alaturqua** [comment]
After sending back the broken card and getting a new one wifi and bluetooth are working perfectly. 

I kind have issues with mouse and audio. Mouse is moving somehow stutterly. And when I move my mouse audio is stuttering as well.

**Comment by alaturqua** [comment]
Update: 

I updated openCore from your repo and Big Sur over the App Store. I had to add USBInjectAll kext to make Bluetooth work again.

Mouse seems to work better now. But I have to test audio stutters over some days.

**Comment by dongcodebmt** [comment]
See this guide to mapping your USB port: https://dortania.github.io/OpenCore-Post-Install/usb/intel-mapping/intel.html
For your mouse and audio. I don't know why. Try to reset NVRAM

**Comment by alaturqua** [comment]
Some more weird issues:

- Netflix not working
- Apple TV+ can't play videos

I guess, this is DRM issue. Do you know maybe how to solve that part?

**Comment by dongcodebmt** [comment]
https://dortania.github.io/OpenCore-Post-Install/universal/drm.html#testing-hardware-acceleration-and-decoding

> Note: Safari 14 and macOS 11, Big Sur are currently unsupported by WhateverGreen's DRM patches. Safari 13 in Catalina and older are supported just fine however.

The solution with Netflix is to use Chrome
Apple TV + probably won't work

**Comment by dongcodebmt** [comment]
> DRM Issues: With Haswell and newer iGPUs, DRM is outright broken on them with macOS Catalina. This includes iTunes Movies, Apple TV+, Amazon Prime and Netflix, the only fix is getting a supported dGPU preferably Polaris or newer that supports HEVC.

https://dortania.github.io/GPU-Buyers-Guide/modern-gpus/intel-gpu.html

The solution with Netflix is to use Chrome
Apple TV + probably won't work

**Comment by dongcodebmt** [comment]
Solved
