### ISSUE TITLE
Wireless BCM94360CS2 + Adapter

### ISSUE THREAD

**Issue by LFMAKER** [dongcodebmt/VX5-591G-OpenCore#7]
Hey bro, i have a vx5 too and i did hackintosh, but my wireless didn't work.
Can you help me with the link for buy this?

**Comment by dongcodebmt** [comment]
If your country doesn't have one. Order from AliExpress or Amazon

Refer to the links below:
https://www.aliexpress.com/item/4000632365086.html
https://www.amazon.com/s?k=bcm94360cs2

**Comment by dongcodebmt** [comment]
Solved
