### ISSUE TITLE
Âm thanh bị nhiễu, biến dạng, rè sau khi wake của cổng headphone

### ISSUE THREAD

**Issue by vacnex** [dongcodebmt/VX5-591G-OpenCore#8]
Chào bạn, 
bạn có bị tình trạng cổng headphone âm thanh bị biến dạng hay rè hay nhiễu sau khi wake laptop ko ?
mình hay cắm hedphone về để máy sleep sau đó wake up thì đôi khi sẽ bị như miêu tả đôi thì thì không. Restart lại là bình thường lại hết. 
Kext codeccommander liệu có fix được vấn đề này không ?
Layout-id đang dùng là 29 thì loa ngoài rất bé, bé hơn bên window hẳn luôn.

**Comment by dongcodebmt** [comment]
Tai nghe thì mình sẽ kiểm tra lại sau. Vì mình đang sử dụng tai nghe không dây
Codeccommander mình cũng không biết có thể fix được không. Bạn có thể thử
Bên mac âm thanh bé vì không có Dolby Atmos như trên win. Bạn cài thêm Boom 3D âm thanh sẽ lớn và hay hơn

**Comment by vacnex** [comment]
Mình cài Boom 3D sau đó boom 3d yêu cầu cài thêm Boom audio component thì mình bị mất âm thanh, gỡ boom 3d ra vẫn mất âm thanh. Cài lại Cata qua recovery cũng không fix được mất âm thanh.
Mình đành xóa trắng lại bigsur thì âm thanh hoạt động lại, mình cài lại boom 3d nhưng ko cài thêm Boom audio component thì tinh chỉnh không có tác dụng?
Codeccommander hình như không có tác dụng thì phải, mình cài lại vẫn chưa thấy thay đổi gì

**Comment by dongcodebmt** [comment]
Bạn vào maclife tải bản mới nhất về
Ngoài ra bạn thử layout-id 31 thử xem

**Comment by vacnex** [comment]
![image](https://user-images.githubusercontent.com/37587399/99879597-98eb0400-2c40-11eb-9556-1d215cb1eefd.png)
Bạn có cài audio component này không ? mình cài mỗi boom 3d thì âm vẫn không có thay đổi
Mình sợ cài vào mất âm thanh lại phải reinstall mac.

**Comment by dongcodebmt** [comment]
Có cài nha bạn

**Comment by vacnex** [comment]
Đã cài được rồi
cám ơn bạn

**Comment by dongcodebmt** [comment]
Mình đã tìm ra nguyên nhân và đang kiểm tra.
Mình đã tạo 1 LayoutId mới và sử dụng cùng với ComboJack.
