### ISSUE TITLE
 Xcode communication does not work (USB-C)

### ISSUE THREAD

**Issue by LFMAKER** [dongcodebmt/VX5-591G-OpenCore#9]
After some tests I saw that xcode does not recognize the iphone 11 when using usb c.

Does any developer have the same problem?

**Comment by LFMAKER** [comment]
Now I have no way to test, but someone already transfer data with usb c?

**Comment by dongcodebmt** [comment]
I don't have a device to map it

Let's replace USBMap.kext with USBInjectAll.kext. 
https://bitbucket.org/RehabMan/os-x-usb-inject-all/downloads/
Restart and use hackintool to check
https://imgur.com/Bni7fEp
Then you can tell me which port it is and I will fix it

You can follow this guide to map your USB port: https://github.com/corpnewt/USBMap

**Comment by LFMAKER** [comment]
Thanks!
As soon as possible I will test and give feedback.
